// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_path_ from "./routes/[...path].tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $admin_index from "./routes/admin/index.tsx";
import * as $api_admin_users from "./routes/api/admin/users.ts";
import * as $api_image from "./routes/api/image.ts";
import * as $api_me from "./routes/api/me.ts";
import * as $api_notes from "./routes/api/notes.ts";
import * as $api_notes_id_ from "./routes/api/notes/[id].ts";
import * as $api_series from "./routes/api/series.ts";
import * as $api_series_id_ from "./routes/api/series/[id].ts";
import * as $api_series_id_image_upload from "./routes/api/series/[id]/image/upload.ts";
import * as $api_series_seriesId_books from "./routes/api/series/[seriesId]/books.ts";
import * as $api_series_seriesId_books_bookId_ from "./routes/api/series/[seriesId]/books/[bookId].ts";
import * as $api_series_seriesId_books_bookId_chapters from "./routes/api/series/[seriesId]/books/[bookId]/chapters.ts";
import * as $api_series_seriesId_books_bookId_chapters_chapterId_ from "./routes/api/series/[seriesId]/books/[bookId]/chapters/[chapterId].ts";
import * as $api_series_seriesId_books_bookId_chapters_chapterId_scenes from "./routes/api/series/[seriesId]/books/[bookId]/chapters/[chapterId]/scenes.ts";
import * as $api_series_seriesId_books_bookId_image_upload from "./routes/api/series/[seriesId]/books/[bookId]/image/upload.ts";
import * as $api_series_seriesId_books_bookId_items_reorder from "./routes/api/series/[seriesId]/books/[bookId]/items/reorder.ts";
import * as $api_series_seriesId_books_bookId_scenes from "./routes/api/series/[seriesId]/books/[bookId]/scenes.ts";
import * as $api_series_seriesId_books_bookId_scenes_sceneId_ from "./routes/api/series/[seriesId]/books/[bookId]/scenes/[sceneId].ts";
import * as $api_series_seriesId_books_bookId_scenes_sceneId_move from "./routes/api/series/[seriesId]/books/[bookId]/scenes/[sceneId]/move.ts";
import * as $api_series_seriesId_character_types from "./routes/api/series/[seriesId]/character-types.ts";
import * as $api_series_seriesId_character_types_typeId_ from "./routes/api/series/[seriesId]/character-types/[typeId].ts";
import * as $api_series_seriesId_characters from "./routes/api/series/[seriesId]/characters.ts";
import * as $api_series_seriesId_characters_characterId_ from "./routes/api/series/[seriesId]/characters/[characterId].ts";
import * as $api_series_seriesId_characters_characterId_image_presign_2 from "./routes/api/series/[seriesId]/characters/[characterId]/image/presign 2.ts";
import * as $api_series_seriesId_characters_characterId_image_upload from "./routes/api/series/[seriesId]/characters/[characterId]/image/upload.ts";
import * as $api_series_seriesId_events from "./routes/api/series/[seriesId]/events.ts";
import * as $api_series_seriesId_events_eventId_ from "./routes/api/series/[seriesId]/events/[eventId].ts";
import * as $api_series_seriesId_locations from "./routes/api/series/[seriesId]/locations.ts";
import * as $api_series_seriesId_locations_locationId_ from "./routes/api/series/[seriesId]/locations/[locationId].ts";
import * as $api_series_seriesId_locations_locationId_image_upload from "./routes/api/series/[seriesId]/locations/[locationId]/image/upload.ts";
import * as $api_series_seriesId_tags from "./routes/api/series/[seriesId]/tags.ts";
import * as $api_series_seriesId_timelines from "./routes/api/series/[seriesId]/timelines.ts";
import * as $api_series_seriesId_timelines_timelineId_ from "./routes/api/series/[seriesId]/timelines/[timelineId].ts";
import * as $api_series_seriesId_timelines_timelineId_events from "./routes/api/series/[seriesId]/timelines/[timelineId]/events.ts";
import * as $api_series_seriesId_timelines_timelineId_events_eventId_ from "./routes/api/series/[seriesId]/timelines/[timelineId]/events/[eventId].ts";
import * as $api_series_seriesId_timelines_timelineId_events_eventId_reorder from "./routes/api/series/[seriesId]/timelines/[timelineId]/events/[eventId]/reorder.ts";
import * as $auth_callback from "./routes/auth/callback.ts";
import * as $auth_signin from "./routes/auth/signin.ts";
import * as $auth_signout from "./routes/auth/signout.ts";
import * as $index from "./routes/index.tsx";
import * as $series_seriesId_books_bookId_ from "./routes/series/[seriesId]/books/[bookId].tsx";
import * as $series_seriesId_books_bookId_settings from "./routes/series/[seriesId]/books/[bookId]/settings.tsx";
import * as $series_seriesId_character_types from "./routes/series/[seriesId]/character-types.tsx";
import * as $series_seriesId_character_types_typeId_ from "./routes/series/[seriesId]/character-types/[typeId].tsx";
import * as $series_seriesId_character_types_new from "./routes/series/[seriesId]/character-types/new.tsx";
import * as $series_seriesId_characters from "./routes/series/[seriesId]/characters.tsx";
import * as $series_seriesId_events from "./routes/series/[seriesId]/events.tsx";
import * as $series_seriesId_index from "./routes/series/[seriesId]/index.tsx";
import * as $series_seriesId_locations from "./routes/series/[seriesId]/locations.tsx";
import * as $series_seriesId_timelines from "./routes/series/[seriesId]/timelines.tsx";
import * as $series_seriesId_timelines_timelineId_ from "./routes/series/[seriesId]/timelines/[timelineId].tsx";
import * as $series_index from "./routes/series/index.tsx";
import * as $AdminDashboard from "./islands/AdminDashboard.tsx";
import * as $BookCoverUploader from "./islands/BookCoverUploader.tsx";
import * as $CharacterForm from "./islands/CharacterForm.tsx";
import * as $CharacterImageUploader from "./islands/CharacterImageUploader.tsx";
import * as $CharacterTypeEditor from "./islands/CharacterTypeEditor.tsx";
import * as $DraggableList from "./islands/DraggableList.tsx";
import * as $EventForm from "./islands/EventForm.tsx";
import * as $HierarchicalSceneList from "./islands/HierarchicalSceneList.tsx";
import * as $ImageUploader from "./islands/ImageUploader.tsx";
import * as $KeyValueEditor from "./islands/KeyValueEditor.tsx";
import * as $SceneList from "./islands/SceneList.tsx";
import * as $TagInput from "./islands/TagInput.tsx";
import * as $ThemeController from "./islands/ThemeController.tsx";
import * as $_stories_CharacterForm_stories from "./islands/__stories__/CharacterForm.stories.tsx";
import * as $_stories_CharacterImageUploader_stories from "./islands/__stories__/CharacterImageUploader.stories.tsx";
import * as $_stories_CharacterTypeEditor_stories from "./islands/__stories__/CharacterTypeEditor.stories.tsx";
import * as $_stories_DraggableList_stories from "./islands/__stories__/DraggableList.stories.tsx";
import * as $_stories_EventForm_stories from "./islands/__stories__/EventForm.stories.tsx";
import * as $_stories_KeyValueEditor_stories from "./islands/__stories__/KeyValueEditor.stories.tsx";
import * as $_stories_SceneList_stories from "./islands/__stories__/SceneList.stories.tsx";
import * as $_stories_ThemeController_stories from "./islands/__stories__/ThemeController.stories.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[...path].tsx": $_path_,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/admin/index.tsx": $admin_index,
    "./routes/api/admin/users.ts": $api_admin_users,
    "./routes/api/image.ts": $api_image,
    "./routes/api/me.ts": $api_me,
    "./routes/api/notes.ts": $api_notes,
    "./routes/api/notes/[id].ts": $api_notes_id_,
    "./routes/api/series.ts": $api_series,
    "./routes/api/series/[id].ts": $api_series_id_,
    "./routes/api/series/[id]/image/upload.ts": $api_series_id_image_upload,
    "./routes/api/series/[seriesId]/books.ts": $api_series_seriesId_books,
    "./routes/api/series/[seriesId]/books/[bookId].ts":
      $api_series_seriesId_books_bookId_,
    "./routes/api/series/[seriesId]/books/[bookId]/chapters.ts":
      $api_series_seriesId_books_bookId_chapters,
    "./routes/api/series/[seriesId]/books/[bookId]/chapters/[chapterId].ts":
      $api_series_seriesId_books_bookId_chapters_chapterId_,
    "./routes/api/series/[seriesId]/books/[bookId]/chapters/[chapterId]/scenes.ts":
      $api_series_seriesId_books_bookId_chapters_chapterId_scenes,
    "./routes/api/series/[seriesId]/books/[bookId]/image/upload.ts":
      $api_series_seriesId_books_bookId_image_upload,
    "./routes/api/series/[seriesId]/books/[bookId]/items/reorder.ts":
      $api_series_seriesId_books_bookId_items_reorder,
    "./routes/api/series/[seriesId]/books/[bookId]/scenes.ts":
      $api_series_seriesId_books_bookId_scenes,
    "./routes/api/series/[seriesId]/books/[bookId]/scenes/[sceneId].ts":
      $api_series_seriesId_books_bookId_scenes_sceneId_,
    "./routes/api/series/[seriesId]/books/[bookId]/scenes/[sceneId]/move.ts":
      $api_series_seriesId_books_bookId_scenes_sceneId_move,
    "./routes/api/series/[seriesId]/character-types.ts":
      $api_series_seriesId_character_types,
    "./routes/api/series/[seriesId]/character-types/[typeId].ts":
      $api_series_seriesId_character_types_typeId_,
    "./routes/api/series/[seriesId]/characters.ts":
      $api_series_seriesId_characters,
    "./routes/api/series/[seriesId]/characters/[characterId].ts":
      $api_series_seriesId_characters_characterId_,
    "./routes/api/series/[seriesId]/characters/[characterId]/image/presign 2.ts":
      $api_series_seriesId_characters_characterId_image_presign_2,
    "./routes/api/series/[seriesId]/characters/[characterId]/image/upload.ts":
      $api_series_seriesId_characters_characterId_image_upload,
    "./routes/api/series/[seriesId]/events.ts": $api_series_seriesId_events,
    "./routes/api/series/[seriesId]/events/[eventId].ts":
      $api_series_seriesId_events_eventId_,
    "./routes/api/series/[seriesId]/locations.ts":
      $api_series_seriesId_locations,
    "./routes/api/series/[seriesId]/locations/[locationId].ts":
      $api_series_seriesId_locations_locationId_,
    "./routes/api/series/[seriesId]/locations/[locationId]/image/upload.ts":
      $api_series_seriesId_locations_locationId_image_upload,
    "./routes/api/series/[seriesId]/tags.ts": $api_series_seriesId_tags,
    "./routes/api/series/[seriesId]/timelines.ts":
      $api_series_seriesId_timelines,
    "./routes/api/series/[seriesId]/timelines/[timelineId].ts":
      $api_series_seriesId_timelines_timelineId_,
    "./routes/api/series/[seriesId]/timelines/[timelineId]/events.ts":
      $api_series_seriesId_timelines_timelineId_events,
    "./routes/api/series/[seriesId]/timelines/[timelineId]/events/[eventId].ts":
      $api_series_seriesId_timelines_timelineId_events_eventId_,
    "./routes/api/series/[seriesId]/timelines/[timelineId]/events/[eventId]/reorder.ts":
      $api_series_seriesId_timelines_timelineId_events_eventId_reorder,
    "./routes/auth/callback.ts": $auth_callback,
    "./routes/auth/signin.ts": $auth_signin,
    "./routes/auth/signout.ts": $auth_signout,
    "./routes/index.tsx": $index,
    "./routes/series/[seriesId]/books/[bookId].tsx":
      $series_seriesId_books_bookId_,
    "./routes/series/[seriesId]/books/[bookId]/settings.tsx":
      $series_seriesId_books_bookId_settings,
    "./routes/series/[seriesId]/character-types.tsx":
      $series_seriesId_character_types,
    "./routes/series/[seriesId]/character-types/[typeId].tsx":
      $series_seriesId_character_types_typeId_,
    "./routes/series/[seriesId]/character-types/new.tsx":
      $series_seriesId_character_types_new,
    "./routes/series/[seriesId]/characters.tsx": $series_seriesId_characters,
    "./routes/series/[seriesId]/events.tsx": $series_seriesId_events,
    "./routes/series/[seriesId]/index.tsx": $series_seriesId_index,
    "./routes/series/[seriesId]/locations.tsx": $series_seriesId_locations,
    "./routes/series/[seriesId]/timelines.tsx": $series_seriesId_timelines,
    "./routes/series/[seriesId]/timelines/[timelineId].tsx":
      $series_seriesId_timelines_timelineId_,
    "./routes/series/index.tsx": $series_index,
  },
  islands: {
    "./islands/AdminDashboard.tsx": $AdminDashboard,
    "./islands/BookCoverUploader.tsx": $BookCoverUploader,
    "./islands/CharacterForm.tsx": $CharacterForm,
    "./islands/CharacterImageUploader.tsx": $CharacterImageUploader,
    "./islands/CharacterTypeEditor.tsx": $CharacterTypeEditor,
    "./islands/DraggableList.tsx": $DraggableList,
    "./islands/EventForm.tsx": $EventForm,
    "./islands/HierarchicalSceneList.tsx": $HierarchicalSceneList,
    "./islands/ImageUploader.tsx": $ImageUploader,
    "./islands/KeyValueEditor.tsx": $KeyValueEditor,
    "./islands/SceneList.tsx": $SceneList,
    "./islands/TagInput.tsx": $TagInput,
    "./islands/ThemeController.tsx": $ThemeController,
    "./islands/__stories__/CharacterForm.stories.tsx":
      $_stories_CharacterForm_stories,
    "./islands/__stories__/CharacterImageUploader.stories.tsx":
      $_stories_CharacterImageUploader_stories,
    "./islands/__stories__/CharacterTypeEditor.stories.tsx":
      $_stories_CharacterTypeEditor_stories,
    "./islands/__stories__/DraggableList.stories.tsx":
      $_stories_DraggableList_stories,
    "./islands/__stories__/EventForm.stories.tsx": $_stories_EventForm_stories,
    "./islands/__stories__/KeyValueEditor.stories.tsx":
      $_stories_KeyValueEditor_stories,
    "./islands/__stories__/SceneList.stories.tsx": $_stories_SceneList_stories,
    "./islands/__stories__/ThemeController.stories.tsx":
      $_stories_ThemeController_stories,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
